# 端口
server:
  port: 9000

# 应用名称
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/Test
    servlet:
      multipart:
        #是否支持批量上传
        enabled: true
        #上传文件最大为 100M
        max-file-size: 100MB
        #上传总数据大小 200M
        max-request-size: 200MB

#eureka:
#  instance:
#    # 使用 ip 代替实例名
#    prefer-ip-address: true
#    # 实例的主机名
#    hostname: ${spring.cloud.client.ip-address}
#    # 实例的 ID 规则
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#  client:
#    serviceUrl:
#      # 注册中心地址
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
